# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'rlmobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rlmobile
  pod 'AppCenterReactNativeShared', '~> 1.0.1'
  pod 'AppCenter/Crashes', '~> 1.0.1'
  pod 'AppCenter/Analytics', '~> 1.0.1'
  pod 'AppCenter/Push', '~> 1.0.1'

  # FB SDK pods
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

end

# This should no longer be needed, react is linked the normal way now.
# post_install do |installer|
#   installer.pods_project.targets.each do |target|

#     if target.name == "React"
#       target.remove_from_project
#     end
#   end
# end